### PR TITLE
enforce function paren and call spacing

### PR DESCRIPTION
**Pull request by tkraak**
Eslint rules to:
- [require or disallow a space before function parenthesis](https://eslint.org/docs/rules/space-before-function-paren)
- [require or disallow spacing between function identifiers and their invocations](https://eslint.org/docs/rules/func-call-spacing)

### CODE REVIEW

**Comment by zoltan-nz** [comment]
Thanks for the PR.

I double checked the default settings in the latest Ember CLI and looks to me, it haven't really changed. There isn't any custom rule in `rules` section.

Usually following the default settings help us to stay close to the framework's conventions. Following the opinionated framework suggestions keep Ember projects consistent.

However, Airbnb Styleguide recommends your custom rules, so it would make sense. https://github.com/airbnb/javascript#functions--signature-spacing

I would rather follow the Ember.js conventions in this case, and change only when the default ember settings will change.

**Comment by tkraak** [comment]
Thanks for checking, leaning on the framework conventions makes sense to me.

That means our rules should be as follows:

```js
'space-before-function-paren': [error, {
      anonymous: 'always',
      named: 'always'
    }],
'func-call-spacing': [ error, 'never']
```

Let me know your thoughts.

**Comment by tkraak** [comment]
@zoltan-nz ... just checking in. How would you like to proceed here? Thx.

**Comment by zoltan-nz** [comment]
@tkraak I think the original (which was provided by the framework) is right and they force the conventional practice. No spaces before the function paren. I think we should keep it that way. If Ember changes the suggested, built in style we just follow the new convention.

Thanks for checking this. I close this PR now.

**Comment by zoltan-nz** [comment]
@tkraak Sorry, I realised your intention was to turn on autofix. So following the Ember convention, maybe we should extend `.eslintrc.js` with the followings: 

```
    'space-before-function-paren': [error, {
      anonymous: 'never',
      named: 'never'
    }],
    'func-call-spacing': [ error, 'never']
```

**Comment by tkraak** [comment]
Thanks. Should be all set now.

**Comment by zoltan-nz** [comment]
Thank you. Looks fantastic. :)

**Pull request merged**
